#!/bin/bash

readonly SITE="$1"
readonly SAVENAME="${SITE//\./_}-$(date +%Y%m%d-%H%M%S)"

trap "_abort; exit 1" 2

function _abort(){
  stty -igncr
  rm -rf "${SAVENAME}.txt" "${SAVENAME}_res.csv"
  echo -ne '\e[1K\r'
  echo "Abort!"
  exit 1
}

function check_sublist3r(){
  command -v sublist3r > /dev/null || {
    cat <<'ERR' >&2 && return 1
Install sublist3r:
  git clone https://github.com/aboul3la/Sublist3r && cd Sublist3r
  pip install -e .
ERR
  }
}

function get_list(){
  echo -ne '\e[5mEnumerating subdomains...\e[m' >&2
  sublist3r -d "$SITE" -o "${SAVENAME}.txt" > /dev/null 2> /dev/null
}

function out_csv(){
  echo -ne '\e[1K\r'
  echo -ne '\e[5mChecking response...(maybe take a while to finish)\e[m' >&2
  echo 'url,res_code,content_type,res_time,redirect_url' > "${SAVENAME}_res.csv"
  < "${SAVENAME}.txt" xargs -n 1 -P 5 -I@ \
    curl "@" -m 2 -s -o /dev/null \
      -w "@,%{http_code},%{content_type},%{time_starttransfer}s,%{redirect_url}\n" |
  sort >> "${SAVENAME}_res.csv"
  echo -ne '\e[1K\r'
}

function usage(){
  echo './sres <domain url>' >&2
}

function main(){
  stty igncr
  { [ $# -eq 1 ] && check_sublist3r;} || { usage && return 1;}
  { get_list && out_csv;} || {
    echo "Error while running!" >&2 && return 1
  }
  echo "Created: ${SAVENAME}.txt, ${SAVENAME}_res.csv" >&2
}

main "$@"
exit $?
